[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmd = "cd backend && pip install -r requirements.txt"

[phases.build]
cmd = "echo 'Build completed'"

[start]
cmd = "cd backend && python app.py"