[build]
builder = "NIXPACKS"
watchPatterns = ["**/*.py", "**/*.txt"]

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "5000" }
PYTHON_VERSION = { default = "3.11" }
