services:
  - type: web
    name: pm-internship-recommender
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start.py"
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
